#!/bin/bash

# Make nano the default editor
export EDITOR="micro"

# Ignore duplicate commands (ignoredups) and lines starting with space in the history
export HISTCONTROL=ignoreboth

# Increase the maximum number of lines contained in the history file (default is 500)
export HISTFILESIZE=200000

# Increase the maximum number of commands to remember (default is 500)
export HISTSIZE=100000

# Don't clear the screen after quitting a manual page
# export MANPAGER="less -X"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

export NCVIEWBASE="${HOME}/.ncmaps/ncmaps/"
