####################
### KEY SETTINGS ###
####################

# Prefix key (remap from 'C-b' to 'C-a')
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix


# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %


# Keys
bind k confirm kill-window
bind K confirm kill-server
bind < resize-pane -L 1
bind > resize-pane -R 1
#bind - resize-pane -D 1
#bind + resize-pane -U 1
bind . command-prompt
bind space command-prompt -p index "select-window"
bind r source-file ~/.tmux.conf   # reload config file


# open session
bind S source-file ~/.tmux/session1


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf


# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# toggle synchronize-panes
# bind C-x setw synchronize-panes
bind g setw synchronize-panes


########################
### GENERAL SETTINGS ###
########################

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on   # only working for >=v2.1
# set -g mouse-resize-pane on
# set -g mouse-select-pane on
# set -g mouse-select-window on
# set -g mode-mouse on


set -g default-terminal "xterm-256color"
# maybe comment the following
# setw -g window-status-current-format '#{?pane_synchronized,#[bg=red],}#I:#W'
# setw -g window-status-format         '#{?pane_synchronized,#[bg=red],}#I:#W'
# setw -g window-status-current-fg colour191
# set -g status-bg default
# set -g status-fg white
# set -g message-bg default
# set -g message-fg colour191

set-window-option -g xterm-keys on

# Highlighting Current Window Using Specified Colour
# set-window-option -g window-status-current-bg yellow

# If you have many tmux windows opened, you might want to get notified when something happens inside other windows.
setw -g monitor-activity on
set -g visual-activity on


######################
### DESIGN CHANGES ###
######################
setw -g automatic-rename off   # rename window to reflect current program
set -g renumber-windows on    # renumber windows when a window is closed
set -g set-titles on          # set terminal title

# For Yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

###############
### PLUGINS ###
###############

# Plugins to use
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'dracula/tmux'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Install tpm and plugins automatically when tmux is started                                                                                                                                                                                                       
# https://github.com/tmux-plugins/tpm/blob/master/docs/automatic_tpm_installation.md                                                                                                                                                                               
# if "test ! -d ~/.tmux/plugins/tpm" \                                                                                                                                                                                                                               
#    "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"                                                                                                                                            


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
