#!/bin/bash

# if $SP1 is non-empty, then load .bash_profile
[ -n "$PS1" ] && source ~/.bash_profile;

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/markusritschel/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/markusritschel/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/markusritschel/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/markusritschel/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/markusritschel/miniconda3/etc/profile.d/mamba.sh" ]; then
    . "/home/markusritschel/miniconda3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<


. "$HOME/.local/bin/env"
